### PR TITLE
Update to latest version

### LINKED ISSUE #2: update to master
please update to master

### PR DESCRIPTION
**Pull request by Kreijstal**
I update to latest version here, and use github actions that does the following.
generates the interpreter file automatically.
bundles it.
tests 2+2 using the interpreter, ("it works")
uploads the files as artifacts to github actions.
This will also activate for any pull requests once github actions is activated so it checks automatically if it works.
If you want to see how the actions look, please take a look at https://github.com/Kreijstal/js-interpreter2/actions/runs/8389849268/job/22976896523
This fixes #2

### CODE REVIEW

**Comment by mercmobily** [comment]
Thanks for the pull request.
Now... a few notes.

# Building
I am 100000% against using Webpack.
If you see the source code of JS-Interpreter (Neil's one), you will see that he actually added a way to decide where the interpreter will be added. He called it `globalThis`. So, the module already comes with its own way to decide what namespace is "polluted"
In order to make the module work 100% for the browsers and for the server, all we need to do is prepend this:

```
var globalThis
if (typeof exports === 'undefined') {
  globalThis = window
} else {
  globalThis = exports
  globalThis.acorn = require('./acorn.js')
}
```

Since Neil provided `globalThis`, this is how the module is meant to be used. Just adding this at the very beginning of it will ensure that either `window` or `exports` is enriched with `Interpreter` and `acorn`, which is exactly what we want

The solution of live patching the main file is against many best practices, and I am 99% sure it will break soon enough.

# Latest version

I have now added Neil's JS-Interpreter as a GIT submodule. So, updating to the latest one is much easier. Unfortunately Neil doesn't provide an NPM version of it. So, the latest version is whatever the last commit is. I will make sure to update this once a month.

# Tests
Having tests would be grand. I will surely accept a PR that will add a "2 + 2" test.

Please try out the latest published version, and confirm that it works.

**Comment by Kreijstal** [comment]
>The solution of live patching the main file is against many best practices, and I am 99% sure it will break soon enough.

You can check the file every day with a chron job, and it will notify you once it breaks, here only 4 lines are patched, not a big deal.

That is essentially what UMD does, it decides on runtime.. am I getting called from CJS? requirejs? amd? or from browser? it is not compatible with esm unfortunately.

**Comment by mercmobily** [comment]
Please have a look at what I did. The main issue is that js-interpreter already has code that is there to make sure it can be used in different ways. With the latest changes (which Neil made to simplify this kind of situation) is to add this:

````
var globalThis
if (typeof exports === 'undefined') {
  globalThis = window
} else {
  globalThis = exports
  globalThis.acorn = require('./acorn.js')

  // This is important as JS-Interpreter assumes that the "global" scope
  // includes primitive variable types
  globalThis.String = String
  globalThis.Date = Date
  globalThis.Boolean = Boolean
  globalThis.Number = Number
  globalThis.RegExp = RegExp
}
````
I am not sure how smart Webpack is, but this is really all that's needed to make it all work -- and it's using exactly the mechanisms provided by js-interpreter.

I will talk to Neil to make things easier, and maybe -- I say maybe -- I will convince him to support Node directly. The deal I had with them was that I made the least number of changes to make it work with Node, with as little magic as possible. Hence this.

**Comment by mercmobily** [comment]
Plus frankly, at this point in time we really need to only worry about CJS and Browser. EMS would require live-patching which is -- again -- against the module's philosophy. If you have a Node project done in ESM, then you can import CJS anyway. Bot the browser no, it's not ideal, but I very much doubt JS-Interpreter will ever shift to ESM, so...

**Pull request closed without merging**
